### Register

POST http://localhost:8080/register/user
Accept: application/json
Content-Type: application/json

{
  "username": "user",
  "password": "password",
  "role": "USER"
}
### Auth

POST http://localhost:8080/auth
Accept: application/json
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}
